name: ml-challenge
channels:
- pytorch
- conda-forge
dependencies:
- python=3.8
- pandas=1.3
- pyarrow=4.0
- matplotlib=3.4
- plotly=5.1
- scipy=1.7
- numpy=1.21
- scikit-learn=0.24
- holidays=0.11
- convertdate=2.3
- python-dateutil=2.8
- luigi=3.0
- tqdm=4.61
- jupyterlab=3.0
- ipywidgets=7.6
- psutil=5.8
- cudatoolkit=11.1
- pytorch=1.9
- pytorch-lightning=1.4
- wandb=0.11
- jsonlines=2.0
- pyspark=3.1
- pip
- pip:
  - gluonts==0.8.0
  - pytorchts==0.5.1
  - tweedie==0.0.7
